### ISSUE TITLE
FR: Show "plan-only" runs in the "runs" overview

### ISSUE THREAD

**Issue by pat-s** [leg100/otf#296]
Maybe not showing them is on purpose - but I'd be great to have at least an option to change this :)

**Comment by leg100** [comment]
Yes, OTF adopts TFC's behaviour:

"Speculative plans are plan-only runs: they show a set of possible changes (and check them against Sentinel policies), but cannot apply those changes. They can begin at any time without waiting for other runs, since they don't affect real infrastructure. Speculative plans do not appear in a workspace's list of runs; viewing them requires a direct link, which is provided when the plan is initiated."

https://developer.hashicorp.com/terraform/cloud-docs/run/remote-operations#speculative-plans

I'll consider implementing a site-wide override option.

**Comment by pat-s** [comment]
I see. Maybe there's a difference between speculative plans and `terraform plan` trigger via CLI?
I was referring to the latter, which are shown in the run overview in TF cloud (run in the middle):

![image](https://user-images.githubusercontent.com/8430564/217577526-f05c7688-2353-4097-967a-3e5e67d557e0.png)

I've also just tried to trigger a "plan-only" from the UI and it also shows up in the run overview list:

![image](https://user-images.githubusercontent.com/8430564/217577924-692a9a34-c47d-41c2-a349-cb355f1f64cd.png)

**Comment by leg100** [comment]
OK, I've had a look into this. The TFC documentation is now out-of-date and incorrect. According to this [support article](https://support.hashicorp.com/hc/en-us/articles/8015488315667-How-to-View-Speculative-Plans-only-in-Terraform-Cloud-UI-Run-List), speculative runs are now visible in the run listing on the Web UI:

> Terraform Cloud (TFC) speculative plans are plan-only runs and cannot be applied [a]. Due to a recent TFC update, speculative plans will now be included within the TFC UI workspace run list.  This list now contains all recent runs mixed with speculative plans [b]. 

I'll make OTF fall into line and include them in the listing as well.

**Comment by leg100** [comment]
Deployed in v0.0.27
