### ISSUE TITLE
Failed to read logs: dial tcp 172.17.0.1:8080: connect: connection refuse

### ISSUE THREAD

**Issue by pat-s** [leg100/otf#305]
I've moved OTF to a single VM (coming from k8s) and currently facing some issues proxying the logs.

```

Waiting for the plan to start...

╷
│ Error: Failed to read logs: dial tcp 172.17.0.1:8080: connect: connection refused
│ 
│ Terraform Cloud returned an unexpected error. Sometimes this is caused by network connection problems, in which case you could
│ retry the command. If the issue persists please open a support ticket to get help resolving the problem.
```

The plan runs fine in the remote and the link pointing to it is also ok.

`172.17.0.1:8080` is the docker0 gateway used by the NGINX reverse proxy sitting in front. I am not quite sure from which the source of this call originates: my local machine (in which the address would ofc be non-valid) or the VM running OTF (for which it should probably be `127.0.0.1:8080` then). 
`OTF_HOSTNAME` is defined in the container but might be unrelated for this.

Is there something additional I am overlooking which I must set so that this request is routed correctly?

v0.0.28

**Comment by leg100** [comment]
OTF uses the following steps to determine the hostname to use for tailing logs:

1. If the `X-Forwarded-Host` header is set  then it'll use that.
2. Otherwise, it uses the `Host` header.

In your case it looks like the `X-Forwarded-Host` header is not being set and it is using the `Host` header instead. Which is not what you want. Your NGINX reverse proxy should really be setting the `X-Forwarded-Host` header automatically.

**Comment by pat-s** [comment]
Thanks!

I've adjusted the headers and can confirm the following works

```
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
```
