### ISSUE TITLE
support for gitea

### ISSUE THREAD

**Issue by markopolo123** [leg100/otf#342]
Awesome Project!

Would you be interested in this project supporting Gitea for auth and teams/org sync?

**Comment by leg100** [comment]
Hello and thank you.

If you wanted to submit a PR, sure.

A couple of things to bear in mind:

* I'm about to merge in a major refactor that you'll want to wait for
* After that I'm going to be adding the ability to manually add/remove orgs and teams and users. Auto-synchronisation would be then be made optional, probably something you'd enable with a CLI flag.

Another thing to bear in mind: I think auto-sync is quite nice for github because github already has the concept of organizations and teams and so that syncs quite nicely. Whereas the gitlab sync isn't so nice because it has no concept of teams and instead otf maps gitlab "access levels" to otf teams, which is a bit naff. I'm don't know anything about Gitea but this is something to bear in mind when designing a solution.

**Comment by pat-s** [comment]
I was thinking about this again just right now - maybe this can be reopened as a feature request?

FWIW, Gitea is very similar WRT to permissions (orgs, teams) to GH. Should be straight forward or at least much easier than GitLab.

**Comment by leg100** [comment]
It should already be possible to use Gitea to login to OTF, using OIDC:

https://docs.otf.ninja/latest/auth/providers/oidc/
https://docs.gitea.com/next/development/oauth2-provider

**Comment by pat-s** [comment]
Thanks! I was referring to Gitea as a VCS provider, not for login (this I already handle via OIDC).
