### ISSUE TITLE
Production ready setup ? 

### ISSUE THREAD

**Issue by rgarrigue** [leg100/otf#468]
Hi there

OTF seems a very nice tool, but I've a bunch of questions before it become a viable option for the company I'm working at. I though it'd make for a nice public discussion, maybe documentation improvements later.

First is, how mature is it ? Is it production ready, or too much moving part / instabilities ?

Then, how do you solve the chickens & eggs problem, aka "How do you deploy the tool that will deploy the infrastructure" ? ATM I'm thinking about going Terraform + Terragrunt with S3 + DynamoDB, also because I can start it from scratch from my laptop. I guess I can run OTF locally, deploy the initial RDS postgres & EKS, deploy OTF there, then migrate state from local to online ?

And finally the disaster scenario, let's say the EC2 / EKS / whatever running OTF is KO, and all I have is a database dump. How do I get my Terraform running existing against the existing states so I can fix stuff ?

Thanks for the FOSS work 🙏🏿

**Comment by rgarrigue** [comment]
And about the stability, any issues ? Or it's stable enough ? Are the upgrade rolling fine so far ? I guess my questions boils 
down to, will it reach v1 somewhen soon ?

**Comment by leg100** [comment]
Hello @rgarrigue.

> And about the stability, any issues ? Or it's stable enough ? Are the upgrade rolling fine so far ? I guess my questions boils down to, will it reach v1 somewhen soon ?

For a v1 I would expect:

* Multiple maintainers who are thoroughly aquainted with the codebase. Currently that is only me, with a few contributors.
* Deployed in several organizations, each deployment in use "for some time" by a team, providing confidence that OTF operates  in different contexts without issues. Of course, I'm relying on organizations to provide feedback, as @fsaintjacques has done.
* And various subjective judgements about the maturity of the codebase, the number of issues, the seriousness of issues, the quality of the documentation, etc.

To sum up, I don't think it'll be hitting v1 any time soon. That's not to say it is unstable. But you will have issues and you'll have to be willing to report them. Otherwise hitting v1 is another chicken and egg problem: stability comes about from usage and feedback. (Bear in mind that terraform itself didn't hit v1 until a couple of years ago).

> Then, how do you solve the chickens & eggs problem, aka "How do you deploy the tool that will deploy the infrastructure" ? ATM I'm thinking about going Terraform + Terragrunt with S3 + DynamoDB, also because I can start it from scratch from my laptop. I guess I can run OTF locally, deploy the initial RDS postgres & EKS, deploy OTF there, then migrate state from local to online ?

These are all good questions. Personally I haven't been concerned about "terraforming OTF" and I've been happy to deploy it without terraform, e.g. deploying the OTF helm chart to a k8s cluster provisioned by hand. But obviously terraforming OTF is a more "correct" approach and something that needs documenting. You can of course run OTF locally and use that to deploy a remote OTF deployment. Or it might be worth looking at how Terraform Enterprise is deployed (the self-hosted version of Terraform Cloud). And of course using S3 or any other backend including the local default state backend is legitimate too. Then as you say, migrate the state into OTF, and then OTF can manage itself (as long as any changes don't destroy OTF itself!).

> And finally the disaster scenario, let's say the EC2 / EKS / whatever running OTF is KO, and all I have is a database dump. How do I get my Terraform running existing against the existing states so I can fix stuff ?

@fsaintjacques is right, all state is kept in postgres. You would need to re-deploy OTF and restore the dump. Again, it might be worth looking at what is documented for Terraform Enterprise. But this is a good point you raise and it's something worth documenting. Perhaps it might even be worth writing a tool that extracts state from postgres or a postgres dump.
