### ISSUE TITLE
Hardcode agent concurrency to 1

### ISSUE THREAD

**Issue by leg100** [leg100/otf#538]
I'm considering hard-coding the agent concurrency to 1. Currently it defaults to 5 and is user-configurable. The reasoning is this:

* The agent has an optional plugin cache that the terraform documentation says it not concurrency-safe (I think there are race conditions if there are multiple runs and a plugin is in the process of being downloaded to the cache).
* If run A and B are running concurrently, and run A has persisted sensitive information to the filesystem, then run B could access that information.
* The TFC agent only invokes one run at a time and this would align OTF behaviour and user expectations etc.

And of course this applies to `otfd` as well as `otf-agent`.

If users want further concurrency they can simply fire up more agents. When idle they shouldn't consume any resources beyond polling the daemon for new runs.

**Comment by take-five** [comment]
My 2c

There's currently no built-in agent auto-scaling mechanism in OTF, so if the concurrency is capped at 1, then users will either have to run enough agents to handle peak load (which isn't cost-effective) or build their own auto-scaling. It is a problem in TFE and other competing products, and it is up to users to solve it (which is a giant PITA if you ask me).

From the presented reasoning it seems that from security standpoint OTF agents would benefit more from share-nothing architecture (i.e. each run runs in its own container without sharing the file system with concurrent runs on the same host). In Kubernetes I would spin up a new Pod for every Terraform run, which would also allow me to better distribute workloads across the fleet of physical hosts.

In the current architecture, maybe a simple fork + chroot will suffice, at least for now, but it's likely that as the product evolves, you'll reinvent containers sooner or later.

Perhaps, if you want to keep the agents behavior consistent with TFC, make `concurrency=1` the default value, but give users an option to increase it if they want to? Otherwise, users are bound to run over-provisioned agent pools just to support workload bursts.

**Comment by leg100** [comment]
@take-five I appreciate the benefits you describe. Thus far it has made sense to go with the simplest possible execution model: fork a terraform process. It's not only simple to implement, it's versatile for users; they can deploy it to a VM, fargate, kubernetes, etc.

I intend to provide further execution options. Whatever the approach it needs to remain versatile and as simple as possible. As you say there are multiple benefits:

* security (share-nothing, leverage security features of docker/kubernetes)
* concurrency safe (resources are isolated, e.g. the plugin cache I referred to earlier)
* auto-scaling (kubernetes spawning pods on-demand)
* packaging complimentary software (aws-cli, provisioners, etc)

Anyway, I'm giving this thought as to the best way to go about it. #553 gives a possible answer to the last point on packaging software in a way that works well with docker and kubernetes.

By the way, there is `--sandbox`, which invokes terraform within [bubblewrap](https://github.com/containers/bubblewrap), restricting its privileges. It might be worth looking at that in the interim.

**Comment by leg100** [comment]
In the meantime I'll hold off altering concurrency.
