### ISSUE TITLE
Bundling additional software

### ISSUE THREAD

**Issue by leg100** [leg100/otf#553]
This seems to be on-going request: the ability to give runs access to additionally installed software, for example `helm-git` in https://github.com/leg100/otf/issues/416.

I don't know the correct approach to this.

I don't like the idea of bundling more and more software into the official docker images. Some users may deem more software a security risk. Much of the software will go unused only to make the image more bloated.

And I don't think the approach of building your own docker image with an OTF base image is scalable. Every time there is a new release you need to trigger another build. Which is fine if you've crafted a CI/CD pipeline to do this but that seems an unnecessary burden.

One approach that might work is using your own image and then "parachute" OTF into the image at run-time:

1. Configure OTF with your image
2. Trigger a run
3. OTF starts your image with a bunch of environment variables
4. The image retrieves a binary, say `otf-run`, from the OTF server.
5. The image invokes `otf-run`, and the environment variables provide necessary info and credentials to invoke terraform etc.

I don't know if any well known systems already do this sort of thing (?).

**Comment by Spritekin** [comment]
Hi @leg100 ,
I wouldn't really worry about this. People using OTF are infra engineers and will have some sort of build mechanism to simplify this. I built a small script that build my image and deploys to DockerHub easy.

But if you are still concerned about this, I proposed an example of a Dockerfile which could be built using switches a couple weeks ago, maybe its a good option.

**Comment by leg100** [comment]
@Spritekin can you post a link to the Dockerfile? I can't seem to find it.

Re the proposed process, I should have mentioned that it's also with a view to spawning runs in containers (see the request from another user: https://github.com/leg100/otf/issues/538#issuecomment-1651081134).

**Comment by Spritekin** [comment]
@leg100 
Look at this post before the last comment.
https://github.com/leg100/otf/issues/498

**Comment by Spritekin** [comment]
@leg100 
IMO, OTF is a clone of TFC and TFC works with runners. This is a very common approach for this use case (i.e. github, bitbucket, TFC). The only problem is OTF runner configuration needs a bit more work. It should just allow any pod contact the main OTF API using a bearer token (the same token for all runners) and OTF should register the runners in a list and send work as needed. 
This approach is great because it puts the configuration burden on the user side. Let users to scale up or down as they need using rules, horizontal autoscalers or whatever. They are also free to mount their own disks depending their requirements and infrastructure configuration. If you are using Kubernetes there are plenty of options for this and the user can configure their pods as they want, OTF only needs to provide a base image and open an API.

Now, the approach mentioned in issue #538 is a nice thought and it transforms OTF into a dynamic scheduler pretty much like JenkinsCI. In this case the approach would be like this:
a. Create a ServiceAccount for OTF.
b. Create a ClusterRole allowing pod or job creation.
c. Bind the service account to the role.
d. Start the main OTF with this service account.
e. Install kubectl or any Kube API in the main OTF container.
f. Allow env vars in the main OTF pod so users can configure the executor image/tag/docker credentials. This image should be based in an otf runner but users can adjust as they prefer.
g. When a new run is started, use kubectl or an API to request the cluster to spawn a new job using the provided image.
i. When the job pod starts, it will connect to the main OTF so it can request more job details or to write progress, status and/or write final outputs in the main OTF.
j. Job ends, closes and is done. Any relevant logs can be retrieved from the pod via Kubernetes.

Again, lots of configuration options. The main problem with this approach is that it puts the responsibility of scheduling and management in the OTF side which complicates things (i.e if Kubernetes API changes, you need to change the process, keep the API versions, etc).

My suggestion is, implement the first one. Option 2 is nice but largely unnecessary.

**Comment by leg100** [comment]
> IMO, OTF is a clone of TFC and TFC works with runners. This is a very common approach for this use case (i.e. github, bitbucket, TFC). The only problem is OTF runner configuration needs a bit more work. It should just allow any pod contact the main OTF API using a bearer token (the same token for all runners) and OTF should register the runners in a list and send work as needed.

TFC has agents, as does OTF. They authenticate with an agent token. You can assign that token to as many agents as you like and work is sent as needed.

**Comment by Spritekin** [comment]
@leg100 
Yeah agents. My point is if you integrate tight with Kubernetes you make it harder for you and less flexible for users. Let people setup their agents as they prefer. As it is now users could install the main OTF in ECS with an RDS instance as persistence backend and agents running in dedicated-dirt-cheap-ancient-generation m1 small spot instances sharing a common EFS and it would just work.
I love kubernetes but there is no need to restrict OTF to it.

**Comment by hoshsadiq** [comment]
This is [Hashicorp's approach](https://developer.hashicorp.com/terraform/cloud-docs/run/install-software#only-install-standalone-binaries):

> Terraform Cloud does not allow you to elevate a command's permissions with sudo during Terraform runs. This means you cannot install packages using the worker OS's normal package management tools. However, you can install and execute standalone binaries in Terraform's working directory.

I personally agree with this approach. Giving options to run a custom base image should be enough as well

> I don't think the approach of building your own docker image with an OTF base image is scalable. Every time there is a new release you need to trigger another build. Which is fine if you've crafted a CI/CD pipeline to do this but that seems an unnecessary burden.

I don't think it's up to OTF to worry about this. This is an optional thing that folks can implement. As long as they base their image on the OTF agent image, there rest should be up to them to figure out on how to keep up to date, as long as they have guidelines on what needs to be done.

**Comment by pat-s** [comment]
Porting the discussion back to it's original topic, we are actively building custom daemon and agent images bundling `helm-git` and `aws-cli`:

- https://hub.docker.com/r/cynkra/otfd
- https://hub.docker.com/r/cynkra/otf-agent

Images are rebuilt daily and are based on `alpine/helm:3.12.2` (otfd) and `alpine:3.18` (agent).

(I still think it would be great to list (curated) custom images in the README or a pinned issue. Users will decided for themselves which images are trustworthy/suitable for them).

**Comment by leg100** [comment]
Archiving repo.
