### ISSUE TITLE
Bitbucket Server Support

### ISSUE THREAD

**Issue by robbert229** [leg100/otf#610]
# Introduction

I am filing this task to track the conversation for adding support for bitbucket server. I am planning on dedicating my free time in the evenings to try to hash this out sometime over the next couple of weeks (assuming that @leg100 is open to the addition of this vcs).

**Comment by robbert229** [comment]
First question. It looks like for the webhook handlers that we don't always specify the cloud when emitting a cloud.VCSEvent. Do Should this be set in both?

from the github provider:
https://github.com/leg100/otf/blob/master/internal/github/event_handler.go#L35
```
	// convert github event to an OTF event
	to := cloud.VCSEvent{
		Cloud: cloud.Github,
	}

        // later on we populate the other fields
```

from the gitlab provider:
https://github.com/leg100/otf/blob/master/internal/gitlab/event_handler.go#L45
```
		return &cloud.VCSEvent{
			Branch:        refParts[2],
			CommitSHA:     event.After,
			DefaultBranch: event.Project.DefaultBranch,
		}, nil
```

**Comment by robbert229** [comment]
Second Question: I think that in order to support the bitbucket provider there might need to be some refactoring to the webhook handler interface. The bitbucket webhook events don't emit the `DefaultBranch` information, so assuming that field is required, then I think there is a need to get access to the client so that the handle can hit the bitbucket server api to request the default branch.

**Comment by leg100** [comment]
A couple of points before you proceed further:

* The gitlab support in OTF is piss poor. I would actually be very surprised if anyone is using gitlab as a VCS provider, because I'm not sure how it would work. I would either ignore the gitlab implementation, or fix it :).
* I am in the process of a major refactor of this section of the codebase. By all means continue doing what you're doing. But one of us will have to re-work our PR before merging.

Re bitbucket and DefaultBranch, according to:

https://support.atlassian.com/bitbucket-cloud/docs/event-payloads/

...there is a `push` parameter which includes a `new` and `old` object, which each contain a `name` parameter, which refers to "The name of the branch, tag, named branch, or bookmark.". Not sure if that will do.

Calling the bitbucket API each time an event comes in is best avoided if possible. But if you have to do do that, then by all means refactor the code.

**Comment by robbert229** [comment]
What is your eta on the refactor? I think I can mostly wait, and resolve the conflicts on my side when you are done.

The docs you linked are for bitbucket cloud, which has a different api from bitbucket server. Sadly bitbucket cloud has all the nice bells and whistles, while bitbucket server languishes. 

I will keep in mind your comments about hitting the api each time. Thanks!

**Comment by leg100** [comment]
ETA: can't be sure, I've wrestled with it for a while now. Could be a few days, could be a week or two. It should make it easier to add further VCS providers such as bitbucket however.

**Comment by robbert229** [comment]
@leg100 I see that the GitHub, and gitlab code has seen some changes. Is this area stabilized, and ready for me to cook up the bitbucket support?

**Comment by leg100** [comment]
@robbert229 Yes, please do so. I'm not entirely pleased with the changes I've made. I wanted to make it so that adding support for a vcs provider such a bitbucket would be as simple as adding a `./bitbucket` package, but alas you'll have to add references to such a package in a dozen code paths littered across the project. Don't worry about getting this 100% correct, please chuck up a PR well before its ready and I'll help out where I can.

**Comment by leg100** [comment]
@robbert229 @ncrocfer I've noticed support for BitBucket Server is to be dropped in February:

https://www.atlassian.com/migration/assess/journey-to-cloud

Given this, I wonder if it is worth the effort of adding this integration for it in OTF. Are you guys going to remain with BitBucket Server for some time after Atlassian drop their support?

**Comment by robbert229** [comment]
So the support that they are dropping is for the non cloud, and non data
center version. They are planning on continuing to support the data center.
Their naming is just kinda all over the place

**Comment by leg100** [comment]
Are you saying they are **not** dropping support for the BitBucket \<thing\> that you are using?

**Comment by robbert229** [comment]
Correct. There are no plans for dropping support by atlassian.

**Comment by ncrocfer** [comment]
Hi everyone,

I confirm they drop the support to the BitBucket Server edition, but not the Datacenter one :)

**Comment by GeneMyslinsky** [comment]
Hi @robbert229, I am a bitbucket cloud user and I have been waiting for this to try OTF out. 
Whenever you feel like it's ready for testing let me know.

**Comment by leg100** [comment]
Archiving repo.
